spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reference?serverTimezone=Asia/Seoul
    username: user
    password: 1234
  jpa:
    hibernate:
      auto_quote_keyword: create
      ddl-auto: validate # ?? ?? ???? ??? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
# JWT
jwt:
  secret: Snd0RGVtb0p3dERlbW9Kd3REZW1vSnd0RGVtb0p3dERlbW9Kd3REZW1vSnd0RGVtb0p3dERlbW9Kd3REZW1vSnd0RGVtb0p3dERlbW9Kd3REZW1vSnd0RGVtb0p3dERlbW9Kd3REZW1vSnd0RGVtbw==